const OpenAI = require("openai");
const prisma = require("../config/prisma");


const client = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY
});


const generateContent = async (req, res) => {

    try {

        const {
            businessName,
            contentType,
            tone
        } = req.body;


        const response = {

            output_text: `
            ${contentType} for ${businessName}
        
            Tone: ${tone}
        
            Welcome to ${businessName}!
        
            Here are some marketing ideas:
        
            1. Create engaging social media posts.
            2. Share customer success stories.
            3. Highlight your unique products and services.
            4. Build a strong relationship with your audience.
        
            This content was generated by BrandOS AI.
            `
        
        };
        res.json({

            content: response.output_text
        
        });

        const savedContent = await prisma.content.create({

            data: {
        
                type: contentType,
        
                title: `${businessName} ${contentType}`,
        
                body: response.output_text,
        
                userId: req.user.id
        
            }
        
        });
        
        
        res.json({
        
            content: savedContent.body
        
        });



    } catch(error) {


        console.log("========== CONTENT ERROR ==========");
        console.log(error);
        console.log("===================================");


        res.status(500).json({

            message: error.message

        });

    }

};
const getHistory = async (req, res) => {

    try {

        const history = await prisma.content.findMany({

            where: {

                userId: req.user.id

            },

            orderBy: {

                createdAt: "desc"

            }

        });


        res.json(history);

    } catch (error) {

        res.status(500).json({

            message: error.message

        });

    }

};
module.exports = {

    generateContent,
    getHistory

};