const OpenAI = require("openai");
const prisma = require("../config/prisma");


const client = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY
});


const generateContent = async (req, res) => {

    try {

        const {
            businessName,
            contentType,
            tone
        } = req.body;


        const response = {

            output_text: `
            ${contentType} for ${businessName}
        
            Tone: ${tone}
        
            Welcome to ${businessName}!
        
            Here are some marketing ideas:
        
            1. Create engaging social media posts.
            2. Share customer success stories.
            3. Highlight your unique products and services.
            4. Build a strong relationship with your audience.
        
            This content was generated by BrandOS AI.
            `
        
        };

        
        const savedContent = await prisma.content.create({

            data: {
        
                type: contentType,
        
                title: `${businessName} ${contentType}`,
        
                body: response.output_text,
        
                userId: req.user.id
        
            }
        
        });
        
        
        res.json({
        
            content: savedContent.body
        
        });



    } catch(error) {


        console.log("========== CONTENT ERROR ==========");
        console.log(error);
        console.log("===================================");


        res.status(500).json({

            message: error.message

        });

    }

};
const getHistory = async (req, res) => {

    try {

        const history = await prisma.content.findMany({

            where: {

                userId: req.user.id

            },

            orderBy: {

                createdAt: "desc"

            }

        });


        res.json(history);

    } catch (error) {

        res.status(500).json({

            message: error.message

        });

    }

};

const updateContent = async (req, res) => {

    try {


        const { body } = req.body;


        const updatedContent = await prisma.content.update({

            where: {

                id: Number(req.params.id)

            },

            data: {

                body: body

            }

        });


        res.json(updatedContent);



    } catch(error) {


        res.status(500).json({

            message: error.message

        });


    }

};

const deleteContent = async (req, res) => {

    try {


        const deletedContent = await prisma.content.delete({

            where: {

                id: Number(req.params.id)

            }

        });



        res.json({

            message: "Content deleted successfully",

            deletedContent

        });



    } catch(error) {


        res.status(500).json({

            message: error.message

        });


    }

};

const getContentStats = async (req, res) => {

    try {


        const total = await prisma.content.count({

            where: {

                userId: req.user.id

            }

        });



        const blogPosts = await prisma.content.count({

            where: {

                userId: req.user.id,

                type: "Blog Post"

            }

        });



        const socialPosts = await prisma.content.count({

            where: {

                userId: req.user.id,

                type: "Social Media Caption"

            }

        });



        const emails = await prisma.content.count({

            where: {

                userId: req.user.id,

                type: "Email Campaign"

            }

        });



        res.json({

            total,

            blogPosts,

            socialPosts,

            emails

        });



    } catch(error) {


        res.status(500).json({

            message: error.message

        });


    }

};
const analyzeSEO = async (req, res) => {

    try {


        const content = await prisma.content.findUnique({

            where: {

                id: Number(req.params.id)

            }

        });



        if (!content) {

            return res.status(404).json({

                message: "Content not found"

            });

        }



        // Fake SEO analysis for now

        const seoResult = {

            score: 85,

            keywords: "marketing, business, audience, brand",

            suggestions:
            "Add more relevant keywords and improve content structure."

        };



        const savedSEO = await prisma.sEOAnalysis.upsert({

            where: {

                contentId: content.id

            },


            update: {

                score: seoResult.score,

                keywords: seoResult.keywords,

                suggestions: seoResult.suggestions

            },


            create: {

                score: seoResult.score,

                keywords: seoResult.keywords,

                suggestions: seoResult.suggestions,

                contentId: content.id

            }

        });



        res.json(savedSEO);



    } catch(error) {


        console.log(error);


        res.status(500).json({

            message: error.message

        });


    }

};

module.exports = {

    generateContent,
    getHistory,
    updateContent,
    deleteContent,
    getContentStats,
    analyzeSEO

};