const prisma = require("../config/prisma");


const generateContent = async (req, res) => {

    try {

        const {
            businessName,
            contentType,
            tone
        } = req.body;


        // Fake AI response for BrandOS MVP
        const response = {

            output_text: `
${contentType} for ${businessName}

Tone: ${tone}

Welcome to ${businessName}!

Here are some marketing ideas:

1. Create engaging social media posts.
2. Share customer success stories.
3. Highlight your unique products and services.
4. Build a strong relationship with your audience.

This content was generated by BrandOS AI.
            `.trim()

        };


        const savedContent = await prisma.content.create({

            data: {

                type: contentType,

                title: `${businessName} ${contentType}`,

                body: response.output_text,

                userId: req.user.id

            }

        });


        res.json({

            content: savedContent.body

        });


    } catch (error) {

        console.log("========== CONTENT ERROR ==========");
        console.log(error);
        console.log("===================================");

        res.status(500).json({

            message: error.message

        });

    }

};


const getHistory = async (req, res) => {

    try {

        const history = await prisma.content.findMany({

            where: {

                userId: req.user.id

            },

            orderBy: {

                createdAt: "desc"

            }

        });


        res.json(history);


    } catch (error) {

        res.status(500).json({

            message: error.message

        });

    }

};


const updateContent = async (req, res) => {

    try {

        const contentId = Number(req.params.id);

        const { body } = req.body;


        const existingContent = await prisma.content.findFirst({

            where: {

                id: contentId,

                userId: req.user.id

            }

        });


        if (!existingContent) {

            return res.status(404).json({

                message: "Content not found"

            });

        }


        const updatedContent = await prisma.content.update({

            where: {

                id: contentId

            },

            data: {

                body

            }

        });


        res.json(updatedContent);


    } catch (error) {

        res.status(500).json({

            message: error.message

        });

    }

};


const deleteContent = async (req, res) => {

    try {

        const contentId = Number(req.params.id);


        const existingContent = await prisma.content.findFirst({

            where: {

                id: contentId,

                userId: req.user.id

            }

        });


        if (!existingContent) {

            return res.status(404).json({

                message: "Content not found"

            });

        }


        const deletedContent = await prisma.content.delete({

            where: {

                id: contentId

            }

        });


        res.json({

            message: "Content deleted successfully",

            deletedContent

        });


    } catch (error) {

        res.status(500).json({

            message: error.message

        });

    }

};


const getContentStats = async (req, res) => {

    try {

        const contents = await prisma.content.findMany({

            where: {

                userId: req.user.id

            },

            include: {

                seoAnalysis: true,

                toneAnalysis: true

            }

        });


        const total = contents.length;


        const blogPosts = contents.filter(

            item => item.type === "Blog Post"

        ).length;


        const socialPosts = contents.filter(

            item => item.type === "Social Media Caption"

        ).length;


        const emails = contents.filter(

            item => item.type === "Email Campaign"

        ).length;


        const seoScores = contents

            .filter(item => item.seoAnalysis)

            .map(item => item.seoAnalysis.score);


        const averageSEO = seoScores.length

            ? Math.round(

                seoScores.reduce(
                    (a, b) => a + b,
                    0
                ) / seoScores.length

            )

            : 0;


        const toneConfidence = contents

            .filter(item => item.toneAnalysis)

            .map(item => item.toneAnalysis.confidence);


        const averageToneConfidence = toneConfidence.length

            ? Math.round(

                toneConfidence.reduce(
                    (a, b) => a + b,
                    0
                ) / toneConfidence.length

            )

            : 0;


        res.json({

            total,

            blogPosts,

            socialPosts,

            emails,

            averageSEO,

            averageToneConfidence

        });


    } catch (error) {

        res.status(500).json({

            message: error.message

        });

    }

};


const analyzeSEO = async (req, res) => {

    try {

        const contentId = Number(req.params.id);


        const content = await prisma.content.findFirst({

            where: {

                id: contentId,

                userId: req.user.id

            }

        });


        if (!content) {

            return res.status(404).json({

                message: "Content not found"

            });

        }


        // Fake SEO analysis for BrandOS MVP
        const seoResult = {

            score: 85,

            keywords:
                "marketing, business, audience, brand",

            suggestions:
                "Add more relevant keywords and improve content structure."

        };


        const savedSEO = await prisma.sEOAnalysis.upsert({

            where: {

                contentId: content.id

            },

            update: {

                score: seoResult.score,

                keywords: seoResult.keywords,

                suggestions: seoResult.suggestions

            },

            create: {

                score: seoResult.score,

                keywords: seoResult.keywords,

                suggestions: seoResult.suggestions,

                contentId: content.id

            }

        });


        res.json(savedSEO);


    } catch (error) {

        console.log(error);

        res.status(500).json({

            message: error.message

        });

    }

};


const analyzeTone = async (req, res) => {

    try {

        const contentId = Number(req.params.id);


        const content = await prisma.content.findFirst({

            where: {

                id: contentId,

                userId: req.user.id

            }

        });


        if (!content) {

            return res.status(404).json({

                message: "Content not found"

            });

        }


        // Fake tone analysis for BrandOS MVP
        const toneResult = {

            tone: "Professional",

            confidence: 92

        };


        const savedTone = await prisma.toneAnalysis.upsert({

            where: {

                contentId: content.id

            },

            update: {

                tone: toneResult.tone,

                confidence: toneResult.confidence

            },

            create: {

                tone: toneResult.tone,

                confidence: toneResult.confidence,

                contentId: content.id

            }

        });


        res.json(savedTone);


    } catch (error) {

        console.log(error);

        res.status(500).json({

            message: error.message

        });

    }

};


module.exports = {

    generateContent,

    getHistory,

    updateContent,

    deleteContent,

    getContentStats,

    analyzeSEO,

    analyzeTone

};